apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jrv9rdfq2-nodejs
  janus-idp.io/tekton: jrv9rdfq2-nodejs
  backstage.io/kubernetes-id: jrv9rdfq2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jrv9rdfq2-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
